program: ../multitask_prompting/train.py
method: grid
metric:
  goal: maximize
  name: validation_accuracy
parameters:
  n_epochs:
    value: 10
  eval_every_steps:
    value: 1000
  wandb:
    value: True
  learning_rate:
    values: [1e-6, 1e-5, 1e-4,1e-3,1e-2]
early_terminate:
  type: hyperband
  s: 2
  eta: 3
  max_iter: 10

